- hosts: webserver
  tasks:
  - name: Installing Webserver
    package:
      name: "httpd"
      state: present

  - name: Installing php
    package:
      name: "php"
      state: present

  - name: Copying files to DocumentRoot
    copy:
      src: "index.php"
      dest: "/var/www/html/"

  - name: Starting Webserver
    service:
      name: "httpd"
      state: started

- hosts: loadbalancer
  tasks:
  - name: Installing load-balancer (HA-proxy) software
    package: 
      name: "haproxy"
      state: present

  - name : Configuring haproxy.cfg file
    template:
      src : "haproxy.cfg"
      dest: "/etc/haproxy/haproxy.cfg"
      
  - name : Starting Load-balancer
    service:
      name: "haproxy"
      state: started
